// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleNotebooksInstanceInvalidDataDiskTypeRule checks the pattern is valid
type GoogleNotebooksInstanceInvalidDataDiskTypeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleNotebooksInstanceInvalidDataDiskTypeRule returns new rule with default attributes
func NewGoogleNotebooksInstanceInvalidDataDiskTypeRule() *GoogleNotebooksInstanceInvalidDataDiskTypeRule {
	return &GoogleNotebooksInstanceInvalidDataDiskTypeRule{
		resourceType:  "google_notebooks_instance",
		attributeName: "data_disk_type",
	}
}

// Name returns the rule name
func (r *GoogleNotebooksInstanceInvalidDataDiskTypeRule) Name() string {
	return "google_notebooks_instance_invalid_data_disk_type"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleNotebooksInstanceInvalidDataDiskTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleNotebooksInstanceInvalidDataDiskTypeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleNotebooksInstanceInvalidDataDiskTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleNotebooksInstanceInvalidDataDiskTypeRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val string) error {
			validateFunc := validation.StringInSlice([]string{"DISK_TYPE_UNSPECIFIED", "PD_STANDARD", "PD_SSD", "PD_BALANCED", "PD_EXTREME", ""}, false)

			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				if err := runner.EmitIssue(r, err.Error(), attribute.Expr.Range()); err != nil {
					return err
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
