// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleLookerInstanceInvalidNameRule checks the pattern is valid
type GoogleLookerInstanceInvalidNameRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleLookerInstanceInvalidNameRule returns new rule with default attributes
func NewGoogleLookerInstanceInvalidNameRule() *GoogleLookerInstanceInvalidNameRule {
	return &GoogleLookerInstanceInvalidNameRule{
		resourceType:  "google_looker_instance",
		attributeName: "name",
	}
}

// Name returns the rule name
func (r *GoogleLookerInstanceInvalidNameRule) Name() string {
	return "google_looker_instance_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleLookerInstanceInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleLookerInstanceInvalidNameRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleLookerInstanceInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleLookerInstanceInvalidNameRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val string) error {
			validateFunc := validateRegexp(`^[a-z][a-z0-9-]{0,39}[a-z0-9]$`)

			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				if err := runner.EmitIssue(r, err.Error(), attribute.Expr.Range()); err != nil {
					return err
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
