// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule checks the pattern is valid
type GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule returns new rule with default attributes
func NewGoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule() *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule {
	return &GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule{
		resourceType:  "google_discovery_engine_license_config",
		attributeName: "subscription_term",
	}
}

// Name returns the rule name
func (r *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule) Name() string {
	return "google_discovery_engine_license_config_invalid_subscription_term"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleDiscoveryEngineLicenseConfigInvalidSubscriptionTermRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val string) error {
			validateFunc := validation.StringInSlice([]string{"SUBSCRIPTION_TERM_UNSPECIFIED", "SUBSCRIPTION_TERM_ONE_MONTH", "SUBSCRIPTION_TERM_ONE_YEAR", "SUBSCRIPTION_TERM_THREE_YEARS", "SUBSCRIPTION_TERM_THREE_MONTHS", "SUBSCRIPTION_TERM_FOURTEEN_DAYS", "SUBSCRIPTION_TERM_CUSTOM"}, false)

			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				if err := runner.EmitIssue(r, err.Error(), attribute.Expr.Range()); err != nil {
					return err
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
