// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleComputeTargetSslProxyInvalidProxyHeaderRule checks the pattern is valid
type GoogleComputeTargetSslProxyInvalidProxyHeaderRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleComputeTargetSslProxyInvalidProxyHeaderRule returns new rule with default attributes
func NewGoogleComputeTargetSslProxyInvalidProxyHeaderRule() *GoogleComputeTargetSslProxyInvalidProxyHeaderRule {
	return &GoogleComputeTargetSslProxyInvalidProxyHeaderRule{
		resourceType:  "google_compute_target_ssl_proxy",
		attributeName: "proxy_header",
	}
}

// Name returns the rule name
func (r *GoogleComputeTargetSslProxyInvalidProxyHeaderRule) Name() string {
	return "google_compute_target_ssl_proxy_invalid_proxy_header"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleComputeTargetSslProxyInvalidProxyHeaderRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleComputeTargetSslProxyInvalidProxyHeaderRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleComputeTargetSslProxyInvalidProxyHeaderRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleComputeTargetSslProxyInvalidProxyHeaderRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"NONE", "PROXY_V1", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
