// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule checks the pattern is valid
type GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule returns new rule with default attributes
func NewGoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule() *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule {
	return &GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule{
		resourceType:  "google_access_context_manager_service_perimeter",
		attributeName: "perimeter_type",
	}
}

// Name returns the rule name
func (r *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule) Name() string {
	return "google_access_context_manager_service_perimeter_invalid_perimeter_type"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleAccessContextManagerServicePerimeterInvalidPerimeterTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"PERIMETER_TYPE_REGULAR", "PERIMETER_TYPE_BRIDGE", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
