// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GooglePubsubSchemaInvalidTypeRule checks the pattern is valid
type GooglePubsubSchemaInvalidTypeRule struct {
	resourceType  string
	attributeName string
}

// NewGooglePubsubSchemaInvalidTypeRule returns new rule with default attributes
func NewGooglePubsubSchemaInvalidTypeRule() *GooglePubsubSchemaInvalidTypeRule {
	return &GooglePubsubSchemaInvalidTypeRule{
		resourceType:  "google_pubsub_schema",
		attributeName: "type",
	}
}

// Name returns the rule name
func (r *GooglePubsubSchemaInvalidTypeRule) Name() string {
	return "google_pubsub_schema_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *GooglePubsubSchemaInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GooglePubsubSchemaInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GooglePubsubSchemaInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GooglePubsubSchemaInvalidTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"TYPE_UNSPECIFIED", "PROTOCOL_BUFFER", "AVRO", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
