// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule checks the pattern is valid
type GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleComputeBackendBucketSignedUrlKeyInvalidNameRule returns new rule with default attributes
func NewGoogleComputeBackendBucketSignedUrlKeyInvalidNameRule() *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule {
	return &GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule{
		resourceType:  "google_compute_backend_bucket_signed_url_key",
		attributeName: "name",
	}
}

// Name returns the rule name
func (r *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule) Name() string {
	return "google_compute_backend_bucket_signed_url_key_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleComputeBackendBucketSignedUrlKeyInvalidNameRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		validateFunc := validateRegexp(`^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$`)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
