// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleComputeManagedSslCertificateInvalidTypeRule checks the pattern is valid
type GoogleComputeManagedSslCertificateInvalidTypeRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleComputeManagedSslCertificateInvalidTypeRule returns new rule with default attributes
func NewGoogleComputeManagedSslCertificateInvalidTypeRule() *GoogleComputeManagedSslCertificateInvalidTypeRule {
	return &GoogleComputeManagedSslCertificateInvalidTypeRule{
		resourceType:  "google_compute_managed_ssl_certificate",
		attributeName: "type",
	}
}

// Name returns the rule name
func (r *GoogleComputeManagedSslCertificateInvalidTypeRule) Name() string {
	return "google_compute_managed_ssl_certificate_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleComputeManagedSslCertificateInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleComputeManagedSslCertificateInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleComputeManagedSslCertificateInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleComputeManagedSslCertificateInvalidTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		validateFunc := validation.StringInSlice([]string{"MANAGED", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
