// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleKmsKeyRingImportJobInvalidImportMethodRule checks the pattern is valid
type GoogleKmsKeyRingImportJobInvalidImportMethodRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleKmsKeyRingImportJobInvalidImportMethodRule returns new rule with default attributes
func NewGoogleKmsKeyRingImportJobInvalidImportMethodRule() *GoogleKmsKeyRingImportJobInvalidImportMethodRule {
	return &GoogleKmsKeyRingImportJobInvalidImportMethodRule{
		resourceType:  "google_kms_key_ring_import_job",
		attributeName: "import_method",
	}
}

// Name returns the rule name
func (r *GoogleKmsKeyRingImportJobInvalidImportMethodRule) Name() string {
	return "google_kms_key_ring_import_job_invalid_import_method"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleKmsKeyRingImportJobInvalidImportMethodRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleKmsKeyRingImportJobInvalidImportMethodRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleKmsKeyRingImportJobInvalidImportMethodRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleKmsKeyRingImportJobInvalidImportMethodRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		validateFunc := validation.StringInSlice([]string{"RSA_OAEP_3072_SHA1_AES_256", "RSA_OAEP_4096_SHA1_AES_256"}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
