// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleCloudRunV2ServiceInvalidLaunchStageRule checks the pattern is valid
type GoogleCloudRunV2ServiceInvalidLaunchStageRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleCloudRunV2ServiceInvalidLaunchStageRule returns new rule with default attributes
func NewGoogleCloudRunV2ServiceInvalidLaunchStageRule() *GoogleCloudRunV2ServiceInvalidLaunchStageRule {
	return &GoogleCloudRunV2ServiceInvalidLaunchStageRule{
		resourceType:  "google_cloud_run_v2_service",
		attributeName: "launch_stage",
	}
}

// Name returns the rule name
func (r *GoogleCloudRunV2ServiceInvalidLaunchStageRule) Name() string {
	return "google_cloud_run_v2_service_invalid_launch_stage"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleCloudRunV2ServiceInvalidLaunchStageRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleCloudRunV2ServiceInvalidLaunchStageRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleCloudRunV2ServiceInvalidLaunchStageRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleCloudRunV2ServiceInvalidLaunchStageRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val string) error {
			validateFunc := validation.StringInSlice([]string{"UNIMPLEMENTED", "PRELAUNCH", "EARLY_ACCESS", "ALPHA", "BETA", "GA", "DEPRECATED", ""}, false)

			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				if err := runner.EmitIssue(r, err.Error(), attribute.Expr.Range()); err != nil {
					return err
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
