// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleMonitoringNotificationChannelInvalidVerificationStatusRule checks the pattern is valid
type GoogleMonitoringNotificationChannelInvalidVerificationStatusRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleMonitoringNotificationChannelInvalidVerificationStatusRule returns new rule with default attributes
func NewGoogleMonitoringNotificationChannelInvalidVerificationStatusRule() *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule {
	return &GoogleMonitoringNotificationChannelInvalidVerificationStatusRule{
		resourceType:  "google_monitoring_notification_channel",
		attributeName: "verification_status",
	}
}

// Name returns the rule name
func (r *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule) Name() string {
	return "google_monitoring_notification_channel_invalid_verification_status"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleMonitoringNotificationChannelInvalidVerificationStatusRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		validateFunc := validation.StringInSlice([]string{"VERIFICATION_STATUS_UNSPECIFIED", "UNVERIFIED", "VERIFIED", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
