// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleComputeInterconnectAttachmentInvalidBandwidthRule checks the pattern is valid
type GoogleComputeInterconnectAttachmentInvalidBandwidthRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleComputeInterconnectAttachmentInvalidBandwidthRule returns new rule with default attributes
func NewGoogleComputeInterconnectAttachmentInvalidBandwidthRule() *GoogleComputeInterconnectAttachmentInvalidBandwidthRule {
	return &GoogleComputeInterconnectAttachmentInvalidBandwidthRule{
		resourceType:  "google_compute_interconnect_attachment",
		attributeName: "bandwidth",
	}
}

// Name returns the rule name
func (r *GoogleComputeInterconnectAttachmentInvalidBandwidthRule) Name() string {
	return "google_compute_interconnect_attachment_invalid_bandwidth"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleComputeInterconnectAttachmentInvalidBandwidthRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleComputeInterconnectAttachmentInvalidBandwidthRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleComputeInterconnectAttachmentInvalidBandwidthRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleComputeInterconnectAttachmentInvalidBandwidthRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"BPS_50M", "BPS_100M", "BPS_200M", "BPS_300M", "BPS_400M", "BPS_500M", "BPS_1G", "BPS_2G", "BPS_5G", "BPS_10G", "BPS_20G", "BPS_50G", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
