// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleDataLossPreventionJobTriggerInvalidStatusRule checks the pattern is valid
type GoogleDataLossPreventionJobTriggerInvalidStatusRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleDataLossPreventionJobTriggerInvalidStatusRule returns new rule with default attributes
func NewGoogleDataLossPreventionJobTriggerInvalidStatusRule() *GoogleDataLossPreventionJobTriggerInvalidStatusRule {
	return &GoogleDataLossPreventionJobTriggerInvalidStatusRule{
		resourceType:  "google_data_loss_prevention_job_trigger",
		attributeName: "status",
	}
}

// Name returns the rule name
func (r *GoogleDataLossPreventionJobTriggerInvalidStatusRule) Name() string {
	return "google_data_loss_prevention_job_trigger_invalid_status"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleDataLossPreventionJobTriggerInvalidStatusRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleDataLossPreventionJobTriggerInvalidStatusRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleDataLossPreventionJobTriggerInvalidStatusRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleDataLossPreventionJobTriggerInvalidStatusRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"PAUSED", "HEALTHY", "CANCELLED", ""}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
