// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule checks the pattern is valid
type GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleDataCatalogEntryGroupInvalidEntryGroupIdRule returns new rule with default attributes
func NewGoogleDataCatalogEntryGroupInvalidEntryGroupIdRule() *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule {
	return &GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule{
		resourceType:  "google_data_catalog_entry_group",
		attributeName: "entry_group_id",
	}
}

// Name returns the rule name
func (r *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule) Name() string {
	return "google_data_catalog_entry_group_invalid_entry_group_id"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleDataCatalogEntryGroupInvalidEntryGroupIdRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validateRegexp(`^[A-z_][A-z0-9_]{0,63}$`)

		err = runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssue(r, err.Error(), attribute.Expr.Range())
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
