// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule checks the pattern is valid
type GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
}

// NewGoogleDataCatalogTagTemplateInvalidTagTemplateIdRule returns new rule with default attributes
func NewGoogleDataCatalogTagTemplateInvalidTagTemplateIdRule() *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule {
	return &GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule{
		resourceType:  "google_data_catalog_tag_template",
		attributeName: "tag_template_id",
	}
}

// Name returns the rule name
func (r *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule) Name() string {
	return "google_data_catalog_tag_template_invalid_tag_template_id"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleDataCatalogTagTemplateInvalidTagTemplateIdRule) Check(runner tflint.Runner) error {
	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{{Name: r.attributeName}},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val string) error {
			validateFunc := validateRegexp(`^[a-z_][a-z0-9_]{0,63}$`)

			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				if err := runner.EmitIssue(r, err.Error(), attribute.Expr.Range()); err != nil {
					return err
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
