// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleDnsRecordSetInvalidTypeRule checks the pattern is valid
type GoogleDnsRecordSetInvalidTypeRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleDnsRecordSetInvalidTypeRule returns new rule with default attributes
func NewGoogleDnsRecordSetInvalidTypeRule() *GoogleDnsRecordSetInvalidTypeRule {
	return &GoogleDnsRecordSetInvalidTypeRule{
		resourceType:  "google_dns_record_set",
		attributeName: "type",
	}
}

// Name returns the rule name
func (r *GoogleDnsRecordSetInvalidTypeRule) Name() string {
	return "google_dns_record_set_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleDnsRecordSetInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleDnsRecordSetInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleDnsRecordSetInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleDnsRecordSetInvalidTypeRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		validateFunc := validation.StringInSlice([]string{"A", "AAAA", "CAA", "CNAME", "DNSKEY", "DS", "IPSECVPNKEY", "MX", "NAPTR", "NS", "PTR", "SOA", "SPF", "SRV", "SSHFP", "TLSA", "TXT"}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
