// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package magicmodules

import (
	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// GoogleAppEngineFirewallRuleInvalidActionRule checks the pattern is valid
type GoogleAppEngineFirewallRuleInvalidActionRule struct {
	resourceType  string
	attributeName string
}

// NewGoogleAppEngineFirewallRuleInvalidActionRule returns new rule with default attributes
func NewGoogleAppEngineFirewallRuleInvalidActionRule() *GoogleAppEngineFirewallRuleInvalidActionRule {
	return &GoogleAppEngineFirewallRuleInvalidActionRule{
		resourceType:  "google_app_engine_firewall_rule",
		attributeName: "action",
	}
}

// Name returns the rule name
func (r *GoogleAppEngineFirewallRuleInvalidActionRule) Name() string {
	return "google_app_engine_firewall_rule_invalid_action"
}

// Enabled returns whether the rule is enabled by default
func (r *GoogleAppEngineFirewallRuleInvalidActionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *GoogleAppEngineFirewallRuleInvalidActionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *GoogleAppEngineFirewallRuleInvalidActionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *GoogleAppEngineFirewallRuleInvalidActionRule) Check(runner tflint.Runner) error {
	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		validateFunc := validation.StringInSlice([]string{"UNSPECIFIED_ACTION", "ALLOW", "DENY"}, false)

		return runner.EnsureNoError(err, func() error {
			_, errors := validateFunc(val, r.attributeName)
			for _, err := range errors {
				runner.EmitIssueOnExpr(r, err.Error(), attribute.Expr)
			}
			return nil
		})
	})
}
